import json
from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime, timezone

ROOT_DIR = Path(__file__).resolve().parents[4]
RISK_ARTIFACTS_DIR = ROOT_DIR / "services" / "digital_twin" / "ml" / "artifacts" / "risk_engine"
RISK_EXP_FILE = RISK_ARTIFACTS_DIR / "risk_explanations.json"

from services.digital_twin.risk.factors.factor_types import RiskLevelTier
from services.digital_twin.risk.thresholds.threshold_classifier import threshold_classifier
from services.digital_twin.risk.explanation.risk_explanation_models import (
    RiskConfidenceLevel, RiskLevelPolicyItem, RISK_LEVEL_POLICIES, RiskExplanation
)

class RiskExplanationEngine:
    """Synthesizes unified explanations combining Phase 15 ML SHAP attributions and Phase 16 risk context."""

    def __init__(self, artifacts_dir: Path = RISK_ARTIFACTS_DIR):
        self.artifacts_dir = artifacts_dir
        self.artifacts_dir.mkdir(parents=True, exist_ok=True)
        self.history: List[RiskExplanation] = []

    def evaluate_risk_confidence(
        self,
        has_prediction: bool,
        has_asset: bool,
        has_vulnerability: bool,
        has_impact: bool
    ) -> RiskConfidenceLevel:
        known_count = sum([has_prediction, has_asset, has_vulnerability, has_impact])
        if known_count == 4:
            return RiskConfidenceLevel.HIGH
        elif known_count == 3:
            return RiskConfidenceLevel.MEDIUM
        elif known_count >= 1:
            return RiskConfidenceLevel.LOW
        else:
            return RiskConfidenceLevel.UNKNOWN

    def generate_risk_explanation(
        self,
        risk_id: str,
        prediction_id: str,
        device_id: str,
        threat_probability: float,
        asset_criticality_level: str,
        asset_criticality_weight: float,
        vulnerability_severity_level: str,
        vulnerability_weight: float,
        attack_impact_level: str,
        attack_impact_weight: float,
        risk_score: float,
        xai_threat_explanation: Optional[str] = None,
        xai_contributing_features: Optional[List[str]] = None,
        is_partial_xai: bool = False
    ) -> RiskExplanation:
        # 1. Tier and Policy Lookup
        tier = threshold_classifier.classify(risk_score)
        policy = RISK_LEVEL_POLICIES.get(tier, RISK_LEVEL_POLICIES[RiskLevelTier.LOW])

        # 2. Phase 15 Model Explanation Synthesis (Why the model predicted the threat)
        if xai_threat_explanation and xai_threat_explanation.strip():
            threat_exp = xai_threat_explanation.strip()
        elif xai_contributing_features:
            feats_str = ", ".join(xai_contributing_features[:3])
            threat_exp = f"Threat probability increased primarily because {feats_str} showed significant baseline deviation."
        elif is_partial_xai:
            threat_exp = f"Threat probability was assessed at {threat_probability*100:.1f}%, but detailed local SHAP feature attributions were only partially available."
        else:
            threat_exp = f"Threat probability of {threat_probability*100:.1f}% was generated by the model based on general telemetry deviations."

        # 3. Phase 16 Risk Explanation Synthesis (Why the threat is risky)
        risk_drivers = []
        if threat_probability >= 0.70:
            risk_drivers.append("threat probability is elevated")
        if asset_criticality_weight >= 0.80:
            risk_drivers.append(f"affected asset has {asset_criticality_level} criticality")
        if vulnerability_weight >= 0.70:
            risk_drivers.append(f"active vulnerability severity is {vulnerability_severity_level}")
        if attack_impact_weight >= 0.80:
            risk_drivers.append(f"predicted attack impact is {attack_impact_level}")

        if not risk_drivers:
            risk_drivers.append("low-impact asset conditions and baseline telemetry prevail")

        risk_exp = f"Risk is {tier.value} because {', '.join(risk_drivers)}."

        # 4. Factor Breakdown Data
        breakdown = {
            "threatProbability": f"{threat_probability*100:.1f}%",
            "assetCriticality": f"{asset_criticality_level} — {asset_criticality_weight:.2f}",
            "vulnerability": f"{vulnerability_severity_level} — {vulnerability_weight:.2f}",
            "attackImpact": f"{attack_impact_level} — {attack_impact_weight:.2f}",
            "calculatedRisk": f"{risk_score:.2f} / 100",
            "riskLevel": tier.value
        }

        # 5. Top Risk Factors
        top_factors = [
            f"Threat Probability: {threat_probability*100:.1f}%",
            f"Asset Criticality: {asset_criticality_level}",
            f"Vulnerability: {vulnerability_severity_level}",
            f"Attack Impact: {attack_impact_level}"
        ]

        # 6. Context Confidence
        confidence = self.evaluate_risk_confidence(
            has_prediction=threat_probability is not None,
            has_asset=bool(device_id and asset_criticality_level),
            has_vulnerability=bool(vulnerability_severity_level),
            has_impact=bool(attack_impact_level)
        )

        mitigation = (
            f"Compensating controls active for {device_id}."
            if vulnerability_weight <= 0.40 else
            f"Host {device_id} requires review of exposed network interfaces."
        )

        record = RiskExplanation(
            riskId=risk_id,
            predictionId=prediction_id,
            deviceId=device_id,
            threatExplanation=threat_exp,
            riskExplanation=risk_exp,
            factorBreakdown=breakdown,
            topRiskFactors=top_factors,
            mitigationContext=mitigation,
            riskLevel=tier,
            riskScore=risk_score,
            riskScoreFormatted=f"{risk_score:.2f} / 100.0",
            recommendedAction=policy.recommendedAction,
            riskAssessmentConfidence=confidence
        )

        self.history.append(record)
        self._persist_explanation(record)
        return record

    def _persist_explanation(self, record: RiskExplanation):
        existing = []
        if RISK_EXP_FILE.exists():
            try:
                with open(RISK_EXP_FILE, "r", encoding="utf-8") as f:
                    existing = json.load(f)
            except Exception:
                existing = []

        existing.append(record.model_dump())
        existing = existing[-100:]
        with open(RISK_EXP_FILE, "w", encoding="utf-8") as f:
            json.dump(existing, f, indent=2)

    def clear(self):
        self.history.clear()
        if RISK_EXP_FILE.exists():
            try:
                RISK_EXP_FILE.unlink()
            except Exception:
                pass

risk_explanation_engine = RiskExplanationEngine()