from enum import Enum

class ResponseActionType(str, Enum):
    ISOLATE_DEVICE = "ISOLATE_DEVICE"
    BLOCK_CONNECTION = "BLOCK_CONNECTION"
    DISABLE_SERVICE = "DISABLE_SERVICE"
    QUARANTINE_ENDPOINT = "QUARANTINE_ENDPOINT"
    INCREASE_SECURITY_LEVEL = "INCREASE_SECURITY_LEVEL"
    MARK_DEVICE_AT_RISK = "MARK_DEVICE_AT_RISK"

class ExecutionModeEnum(str, Enum):
    SIMULATION = "SIMULATION"
    REAL = "REAL"

class ResponseStatusEnum(str, Enum):
    RECOMMENDED = "RECOMMENDED"
    PENDING = "PENDING"
    SIMULATING = "SIMULATING"
    APPLIED_TO_TWIN = "APPLIED_TO_TWIN"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"